from abc import ABC

_Real = Real | int | float

class Real(ABC):
    def __set__(self, other: _Real) -> Real: ...

    def __add__(self: Real, other: _Real) -> Real: ...
    def __sub__(self: Real, other: _Real) -> Real: ...
    def __mul__(self: Real, other: _Real) -> Real: ...
    def __truediv__(self: Real, other: _Real) -> Real: ...

    def __radd__(self: Real, other: _Real) -> Real: ...
    def __rsub__(self: Real, other: _Real) -> Real: ...
    def __rmul__(self: Real, other: _Real) -> Real: ...
    def __rtruediv__(self: Real, other: _Real) -> Real: ...

    def __pow__(self: Real, other: int) -> Real: ...

    def __eq__(self: Real, other) -> bool: ...
    def __ne__(self: Real, other) -> bool: ...
    def __lt__(self: Real, other: _Real) -> bool: ...
    def __le__(self: Real, other: _Real) -> bool: ...
    def __gt__(self: Real, other: _Real) -> bool: ...
    def __ge__(self: Real, other: _Real) -> bool: ...

def fabs(x: _Real) -> Real: ...
def sqrt(x: _Real) -> Real: ...
def cbrt(x: _Real) -> Real: ...
def ceil(x: _Real) -> Real: ...
def floor(x: _Real) -> Real: ...
def nearbyint(x: _Real) -> Real: ...
def round(x: _Real) -> Real: ...
def trunc(x: _Real) -> Real: ...
def acos(x: _Real) -> Real: ...
def asin(x: _Real) -> Real: ...
def atan(x: _Real) -> Real: ...
def cos(x: _Real) -> Real: ...
def sin(x: _Real) -> Real: ...
def tan(x: _Real) -> Real: ...
def acosh(x: _Real) -> Real: ...
def asinh(x: _Real) -> Real: ...
def atanh(x: _Real) -> Real: ...
def exp(x: _Real) -> Real: ...
def exp2(x: _Real) -> Real: ...
def expm1(x: _Real) -> Real: ...
def log(x: _Real) -> Real: ...
def log10(x: _Real) -> Real: ...
def log1p(x: _Real) -> Real: ...
def log2(x: _Real) -> Real: ...
def erf(x: _Real) -> Real: ...
def erfc(x: _Real) -> Real: ...
def lgamma(x: _Real) -> Real: ...
def tgamma(x: _Real) -> Real: ...
def isfinite(x: _Real) -> bool: ...
def isinf(x: _Real) -> bool: ...
def isnan(x: _Real) -> bool: ...
def isnormal(x: _Real) -> bool: ...
def signbit(x: _Real) -> bool: ...

def copysign(x: _Real, y: _Real) -> Real: ...
def fdim(x: _Real, y: _Real) -> Real: ...
def max(x: _Real, y: _Real) -> Real: ...
def min(x: _Real, y: _Real) -> Real: ...
def fmod(x: _Real, y: _Real) -> Real: ...
def remainder(x: _Real, y: _Real) -> Real: ...
def hypot(x: _Real, y: _Real) -> Real: ...
def atan2(x: _Real, y: _Real) -> Real: ...
def pow(x: _Real, y: _Real) -> Real: ...

def fma(x: _Real, y: _Real, z: _Real) -> Real: ...

def digits(m: int, e: int, b: int) -> Real: ...
